// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~F:HoehenGenerator.HGTFile.hgtDaten")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~F:HoehenGenerator.Matrix.mInnerMatrix")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~F:HoehenGenerator.ZeichneBitMap.color")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~F:HoehenGenerator.ZwischenspeicherHgt.höhen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.HGTFile.#ctor(System.Int32,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.HGTFile.LeseDaten~System.Int16[,]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.MainWindow.GeneriereEEPBitMap(System.String,System.Int32,System.Int32,System.Drawing.Color,System.Drawing.Imaging.PixelFormat)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.Matrix.#ctor(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.ZeichneBitMap.#ctor(System.Drawing.Bitmap,System.Drawing.Color)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.ZeichneBitMap.#ctor(System.Drawing.Bitmap,System.Drawing.Color[,])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.ZeichneBitMap.colors(System.Int32,System.Int32)~System.Drawing.Color[,]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.ZwischenspeicherHgt.#ctor(HoehenGenerator.GeoPunkt,HoehenGenerator.GeoPunkt,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.ZwischenspeicherHgt.#ctor(HoehenGenerator.GeoPunkt,System.Int32,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.ZwischenspeicherHgt.InterpoliereHöhe(HoehenGenerator.GeoPunkt)~System.Double")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~P:HoehenGenerator.HGTFile.HgtDaten")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~P:HoehenGenerator.ZeichneBitMap.Color")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Ausstehend>", Scope = "member", Target = "~P:HoehenGenerator.ZwischenspeicherHgt.Höhen")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Stil", "IDE0059:Unnötige Zuweisung eines Werts.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.MainWindow.btnAnlagenDirectory_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Stil", "IDE0059:Unnötige Zuweisung eines Werts.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.MainWindow.findeErsteDatei(System.String,System.Boolean)~HoehenGenerator.Filemitauflösung")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Stil", "IDE0059:Unnötige Zuweisung eines Werts.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.MainWindow.FindeZipFiles(System.String)~System.String[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Stil", "IDE0059:Unnötige Zuweisung eines Werts.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.MainWindow.LeseEinUndMachWeiter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Stil", "IDE0059:Unnötige Zuweisung eines Werts.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.MainWindow.ZeichnePolygon(System.Windows.Media.PointCollection,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Stil", "IDE0059:Unnötige Zuweisung eines Werts.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.MainWindow.ZeichnePunkte(System.Windows.Media.PointCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Stil", "IDE0059:Unnötige Zuweisung eines Werts.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.MainWindow.ZeichneRechteck(System.Windows.Media.PointCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Stil", "IDE0059:Unnötige Zuweisung eines Werts.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.VierEcken.BestimmeHgtFile(System.Double,System.Double,System.String)~HoehenGenerator.HgtmitKoordinaten")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Stil", "IDE0059:Unnötige Zuweisung eines Werts.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:HoehenGenerator.ZwischenspeicherHgt.LeseEin(HoehenGenerator.VierEcken,System.String,System.String,HoehenGenerator.FileMitEckKoordinaten)")]